'use client';

import { useState } from 'react';
import { Alert, Badge, Button, cx, fieldClass } from '@/components/ui';

/**
 * The optional AI tutor, as it appears to a learner.
 *
 * Rendered only when the server says the tutor is switched on, and only in
 * places where the server will actually allow it - the button is a
 * convenience, not the access check. Every response is labelled as AI output,
 * sits visually apart from the editors' reviewed explanation, and can be
 * reported.
 */

interface TutorReply {
  responseId: string;
  kind: 'hint' | 'explain' | 'debrief';
  html: string;
  label: string;
  cached: boolean;
  truncated: boolean;
}

type Outcome = { ok: true; reply: TutorReply } | { ok: false; message: string };

async function ask(url: string, body: unknown): Promise<Outcome> {
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'examer' },
      body: JSON.stringify(body),
    });
    const data = (await response.json().catch(() => null)) as
      | (TutorReply & { error?: undefined })
      | { error: { message: string } }
      | null;
    if (response.ok && data && !('error' in data && data.error)) {
      return { ok: true, reply: data as TutorReply };
    }
    const message =
      data && 'error' in data && data.error ? data.error.message : 'The AI tutor is unavailable right now.';
    return { ok: false, message };
  } catch {
    return { ok: false, message: 'Could not reach the AI tutor. Check your connection and try again.' };
  }
}

/** A small mark, so "this is AI" never rests on the badge colour alone. */
function SparkIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <path
        d="M8 1.5l1.6 4.4 4.4 1.6-4.4 1.6L8 13.5 6.4 9.1 2 7.5l4.4-1.6L8 1.5z"
        fill="currentColor"
      />
    </svg>
  );
}

function AiBadge() {
  return (
    <Badge tone="accent">
      <SparkIcon />
      AI tutor
    </Badge>
  );
}

function TutorError({ message }: { message: string }) {
  return (
    <Alert tone="caution" role="alert" className="mt-3">
      <p>{message}</p>
    </Alert>
  );
}

// ---------------------------------------------------------------------------
// One AI response, with its label and a way to report it
// ---------------------------------------------------------------------------

function AiResponse({ reply, title }: { reply: TutorReply; title: string }) {
  const [reporting, setReporting] = useState(false);
  const [details, setDetails] = useState('');
  const [reportState, setReportState] = useState<'idle' | 'sending' | 'sent' | 'failed'>('idle');

  async function report() {
    setReportState('sending');
    const response = await fetch('/api/tutor/flag', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'examer' },
      body: JSON.stringify({ responseId: reply.responseId, details: details.trim() || undefined }),
    }).catch(() => null);
    setReportState(response?.ok ? 'sent' : 'failed');
  }

  const detailsId = `ai-report-${reply.responseId}`;

  return (
    <section
      aria-label={`${title}, generated by AI`}
      className="rounded-card border border-accent-line bg-surface p-5"
    >
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <AiBadge />
        <h3 className="font-heading text-base font-semibold">{title}</h3>
      </div>

      <div className="prose-academic question-text text-sm" dangerouslySetInnerHTML={{ __html: reply.html }} />

      {reply.truncated ? (
        <p className="mt-2 text-xs text-ink-subtle">This response reached its length limit and may end abruptly.</p>
      ) : null}

      <p className="mt-4 border-t border-line pt-3 text-xs leading-relaxed text-ink-subtle">{reply.label}</p>

      <div className="mt-2 text-sm">
        {reportState === 'sent' ? (
          <p role="status" className="text-positive">
            Thank you. An editor will review this response.
          </p>
        ) : reporting ? (
          <div className="mt-2 space-y-2">
            <label htmlFor={detailsId} className="block font-medium">
              What is wrong with it? <span className="font-normal text-ink-muted">(optional)</span>
            </label>
            <textarea
              id={detailsId}
              value={details}
              onChange={(event) => setDetails(event.target.value)}
              maxLength={2000}
              rows={3}
              className={fieldClass('py-2')}
            />
            <div className="flex flex-wrap gap-2">
              <Button size="sm" variant="secondary" onClick={() => void report()} loading={reportState === 'sending'}>
                Send report
              </Button>
              <Button size="sm" variant="quiet" onClick={() => setReporting(false)}>
                Cancel
              </Button>
            </div>
            {reportState === 'failed' ? <TutorError message="The report could not be sent. Please try again." /> : null}
          </div>
        ) : (
          <button
            type="button"
            className="text-ink-muted underline underline-offset-2 hover:text-ink"
            onClick={() => setReporting(true)}
          >
            Report this AI response
          </button>
        )}
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Per-question help: progressive hints, then a deeper explanation
// ---------------------------------------------------------------------------

export function QuestionTutor({
  attemptId,
  partIndex,
  position,
  canHint,
  canExplain,
}: {
  attemptId: string;
  partIndex: number;
  position: number;
  /** Untimed learning session, answer not yet checked. */
  canHint: boolean;
  /** The learner may already see the answer. */
  canExplain: boolean;
}) {
  const [hints, setHints] = useState<TutorReply[]>([]);
  const [explanation, setExplanation] = useState<TutorReply | null>(null);
  const [pending, setPending] = useState<'hint' | 'explain' | null>(null);
  const [error, setError] = useState<string | null>(null);

  if (!canHint && !canExplain) return null;

  async function requestHint() {
    const level = (hints.length + 1) as 1 | 2;
    setPending('hint');
    setError(null);
    const outcome = await ask('/api/tutor/help', { attemptId, partIndex, position, kind: 'hint', level });
    setPending(null);
    if (outcome.ok) setHints((current) => [...current, outcome.reply]);
    else setError(outcome.message);
  }

  async function requestExplanation() {
    setPending('explain');
    setError(null);
    const outcome = await ask('/api/tutor/help', { attemptId, partIndex, position, kind: 'explain' });
    setPending(null);
    if (outcome.ok) setExplanation(outcome.reply);
    else setError(outcome.message);
  }

  const showHints = canHint && !canExplain;

  return (
    <div className="mt-6 space-y-3">
      {showHints
        ? hints.map((hint, index) => <AiResponse key={hint.responseId} reply={hint} title={`Hint ${index + 1} of 2`} />)
        : null}
      {explanation ? <AiResponse reply={explanation} title="A deeper explanation" /> : null}

      <div className={cx('flex flex-wrap items-center gap-3', (hints.length > 0 || explanation) && 'pt-1')}>
        {showHints && hints.length < 2 ? (
          <Button size="sm" variant="secondary" onClick={() => void requestHint()} loading={pending === 'hint'} disabled={pending !== null}>
            {hints.length === 0 ? 'Get a hint' : 'Another hint'}
          </Button>
        ) : null}
        {canExplain && !explanation ? (
          <Button size="sm" variant="secondary" onClick={() => void requestExplanation()} loading={pending === 'explain'} disabled={pending !== null}>
            Explain this in more depth
          </Button>
        ) : null}
        {(showHints && hints.length < 2) || (canExplain && !explanation) ? (
          <span className="flex items-center gap-1.5 text-xs text-ink-muted">
            <SparkIcon />
            {showHints ? 'Optional AI help: points to the method, never the answer.' : 'Optional AI help.'}
          </span>
        ) : null}
      </div>

      {error ? <TutorError message={error} /> : null}
    </div>
  );
}

// ---------------------------------------------------------------------------
// After the test: a study debrief with tips and tricks
// ---------------------------------------------------------------------------

export function DebriefTutor({ attemptId }: { attemptId: string }) {
  const [reply, setReply] = useState<TutorReply | null>(null);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function request() {
    setPending(true);
    setError(null);
    const outcome = await ask('/api/tutor/debrief', { attemptId });
    setPending(false);
    if (outcome.ok) setReply(outcome.reply);
    else setError(outcome.message);
  }

  if (reply) return <AiResponse reply={reply} title="Your after-test guide" />;

  return (
    <div className="rounded-card border border-accent-line bg-surface p-5 sm:p-6">
      <div className="flex flex-wrap items-center gap-2">
        <AiBadge />
      </div>
      <h2 className="mt-3 font-heading text-xl font-semibold">After-test guide</h2>
      <p className="mt-2 max-w-2xl text-sm leading-relaxed text-ink-muted">
        A short study guide built from this session: what went well, where the marks went, and specific tips and
        tricks for the skills you missed. It works only from your results and the questions in this session, and it
        never predicts a score.
      </p>
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Button size="sm" onClick={() => void request()} loading={pending}>
          {pending ? 'Writing your guide' : 'Write my after-test guide'}
        </Button>
        <span className="text-xs text-ink-muted">Optional. Uses one of your daily AI requests.</span>
      </div>
      {error ? <TutorError message={error} /> : null}
    </div>
  );
}
